# Generated by Django 4.0.4 on 2022-06-24 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('delivery_id', models.CharField(max_length=100)),
                ('storage_id', models.CharField(max_length=100)),
                ('recipient_alias', models.CharField(max_length=20)),
                ('storage_pos', models.CharField(max_length=100)),
                ('storage_address', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=10)),
                ('size', models.FloatField()),
                ('storage_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
